create database Flight_Analysis;
use Flight_Analysis;

CREATE TABLE MetaData (
    PASSENGERS BIGINT,FREIGHT BIGINT,MAIL BIGINT,DISTANCE FLOAT,UNIQUE_CARRIER VARCHAR(10),AIRLINE_ID INT,
    UNIQUE_CARRIER_NAME VARCHAR(100),UNIQUE_CARRIER_ENTITY VARCHAR(20),REGION CHAR(1),CARRIER VARCHAR(10),CARRIER_NAME VARCHAR(100),
    CARRIER_GROUP INT,CARRIER_GROUP_NEW INT,ORIGIN_AIRPORT_ID INT,ORIGIN_AIRPORT_SEQ_ID INT,ORIGIN_CITY_MARKET_ID INT,ORIGIN CHAR(3),
    ORIGIN_CITY_NAME VARCHAR(100),ORIGIN_STATE_ABR CHAR(2),ORIGIN_STATE_FIPS INT,ORIGIN_STATE_NM VARCHAR(50),ORIGIN_WAC INT,
    DEST_AIRPORT_ID INT,DEST_AIRPORT_SEQ_ID INT,DEST_CITY_MARKET_ID INT,DEST CHAR(3),DEST_CITY_NAME VARCHAR(100),DEST_STATE_ABR CHAR(2),
    DEST_STATE_FIPS INT,DEST_STATE_NM VARCHAR(50),DEST_WAC INT,YEAR INT,QUARTER INT,MONTH INT,DISTANCE_GROUP INT,CLASS CHAR(1)
);

SHOW GLOBAL VARIABLES LIKE 'local_infile';
SET GLOBAL local_infile = 1;

SHOW VARIABLES LIKE 'secure_file_priv';


LOAD DATA LOCAL INFILE 'C:/Users/Kaiya/OneDrive/Documents/Desktop/Indigo Flight Delay Analysis/Airport_Project_Data.csv'
INTO TABLE MetaData
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\r\n' -- Use '\r\n' for Windows CSV files
IGNORE 1 ROWS;


select count(*) from MetaData;


CREATE TABLE Airline (
    AIRLINE_ID INT PRIMARY KEY,
    UNIQUE_CARRIER VARCHAR(10),
    UNIQUE_CARRIER_NAME VARCHAR(100),
    UNIQUE_CARRIER_ENTITY VARCHAR(10)
);

CREATE TABLE Airport (
    AIRPORT_ID INT PRIMARY KEY,
    AIRPORT_SEQ_ID INT,
    CITY_MARKET_ID INT,
    AIRPORT_CODE VARCHAR(10),
    CITY_NAME VARCHAR(100),
    STATE_ABR CHAR(2),
    STATE_FIPS INT,
    STATE_NM VARCHAR(100),
    WAC INT
);

CREATE TABLE Flight (
    FLIGHT_ID INT AUTO_INCREMENT PRIMARY KEY,
    AIRLINE_ID INT,
    ORIGIN_AIRPORT_ID INT,
    DEST_AIRPORT_ID INT,
    DISTANCE FLOAT,
    DISTANCE_GROUP INT,
    YEAR INT,
    QUARTER INT,
    MONTH INT,
    CLASS CHAR(1),
    FOREIGN KEY (AIRLINE_ID) REFERENCES Airline(AIRLINE_ID),
    FOREIGN KEY (ORIGIN_AIRPORT_ID) REFERENCES Airport(AIRPORT_ID),
    FOREIGN KEY (DEST_AIRPORT_ID) REFERENCES Airport(AIRPORT_ID)
);

CREATE TABLE FlightMetrics (
    FLIGHT_ID INT,
    PASSENGERS FLOAT,
    FREIGHT FLOAT,
    MAIL FLOAT,
    FOREIGN KEY (FLIGHT_ID) REFERENCES Flight(FLIGHT_ID)
);

CREATE TABLE City (
	City_id INT AUTO_INCREMENT PRIMARY KEY,
    CityName VARCHAR(100),
    STATE_ABR CHAR(2),
    State_NM varchar(100) 
    );
select *from City;    
    